runtime: nodejs
env: flex
threadsafe: true
automatic_scaling:
  max_num_instances: 1
env_variables:
  MONGO_URL: 'mongodb://demo1:demo@ds025782.mlab.com:25782/meteor'
  ROOT_URL: 'https://round-terminus-155414'
  METEOR_SETTINGS: '{}'
